[versions]
versionName = "3.0"
hiddenapibypass = "6.1"
shizuku = "13.1.5"
compose-bom = "1.9.4"
activity-compose = "1.12.0-rc01"
lifecycle = "2.10.0-rc01"

[libraries]
shizuku-api = { module = "dev.rikka.shizuku:api", version.ref = "shizuku" }
shizuku-provider = { module = "dev.rikka.shizuku:provider", version.ref = "shizuku" }
hiddenapibypass = { module = "org.lsposed.hiddenapibypass:hiddenapibypass", version.ref = "hiddenapibypass" }

compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
